package enums

// STOPPED, STARTING, SCAN_QR_CODE, WORKING, FAILED
type WAHA_SESSION_STATUS string

const (
	WAHA_SESSION_STOPPED       WAHA_SESSION_STATUS = "STOPPED"
	WAHA_SESSION_STARTING      WAHA_SESSION_STATUS = "STARTING"
	WAHA_SESSION_SCAN_QR_CODE  WAHA_SESSION_STATUS = "SCAN_QR_CODE"
	WAHA_SESSION_WORKING       WAHA_SESSION_STATUS = "WORKING"
	WAHA_SESSION_FAILED        WAHA_SESSION_STATUS = "FAILED"
)

func (s WAHA_SESSION_STATUS) String() string {
	return string(s)
}
